/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rPS6ILNZrmg
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function MainDemoPage() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <div className="border-b bg-gray-100/50 dark:bg-gray-800/50 border-gray-200 dark:border-gray-800">
        <div className="container flex items-center justify-between h-14 px-4 md:px-6">
          <nav className="flex items-center space-x-4">
            <Link className="text-lg font-bold" href="#">
              MemoSphere
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Button variant="link">Sobre</Button>
            <Button>Suporte</Button>
          </div>
        </div>
      </div>
      <div className="flex-1">
        <div className="px-4 md:px-6 lg:px-8 xl:px-12 2xl:px-20 py-6 space-y-6">
          <div className="flex flex-col gap-2">
            <Button className="h-10" variant="outline">
              Partilha uma história
            </Button>
            <div className="grid gap-4">
              <Card>
                <CardHeader className="p-4 flex flex-row items-center">
                  <Link className="flex items-center gap-2 text-sm font-semibold" href="#">
                    <Avatar className="w-8 h-8 border">
                      <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                    </Avatar>
                    Acme Inc
                  </Link>
                  <div className="text-xs ml-auto w-20">2 hours ago</div>
                </CardHeader>
                <CardContent className="p-4">
                  <h2 className="text-xl font-semibold leading-6">The quick brown fox jumps over the lazy dog</h2>
                  <p className="text-sm leading-5 mt-2">
                    The five boxing wizards jump quickly. Pack my box with five dozen liquor jugs.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="p-4 flex flex-row items-center">
                  <Link className="flex items-center gap-2 text-sm font-semibold" href="#">
                    <Avatar className="w-8 h-8 border">
                      <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                    </Avatar>
                    Acme Inc
                  </Link>
                  <div className="text-xs ml-auto w-20">2 hours ago</div>
                </CardHeader>
                <CardContent className="p-4">
                  <h2 className="text-xl font-semibold leading-6">The quick brown fox jumps over the lazy dog</h2>
                  <p className="text-sm leading-5 mt-2">
                    The five boxing wizards jump quickly. Pack my box with five dozen liquor jugs.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="p-4 flex flex-row items-center">
                  <Link className="flex items-center gap-2 text-sm font-semibold" href="#">
                    <Avatar className="w-8 h-8 border">
                      <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                    </Avatar>
                    Acme Inc
                  </Link>
                  <div className="text-xs ml-auto w-20">2 hours ago</div>
                </CardHeader>
                <CardContent className="p-4">
                  <h2 className="text-xl font-semibold leading-6">The quick brown fox jumps over the lazy dog</h2>
                  <p className="text-sm leading-5 mt-2">
                    The five boxing wizards jump quickly. Pack my box with five dozen liquor jugs.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="p-4 flex flex-row items-center">
                  <Link className="flex items-center gap-2 text-sm font-semibold" href="#">
                    <Avatar className="w-8 h-8 border">
                      <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                    </Avatar>
                    Acme Inc
                  </Link>
                  <div className="text-xs ml-auto w-20">2 hours ago</div>
                </CardHeader>
                <CardContent className="p-4">
                  <h2 className="text-xl font-semibold leading-6">The quick brown fox jumps over the lazy dog</h2>
                  <p className="text-sm leading-5 mt-2">
                    The five boxing wizards jump quickly. Pack my box with five dozen liquor jugs.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
