/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cnrL1bfSt4z
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function TextEditorDemo() {
  return (
    <div className="mx-auto prose prose-gray max-w-6xl w-full px-6">
      <div className="space-y-6">
        <div className="space-y-2">
          <h1>Share your story</h1>
          <p>Write your story below. You can format your text using Markdown.</p>
        </div>
        <div className="space-y-4">
          <div>
            <Label htmlFor="title">Title</Label>
            <Input id="title" placeholder="Enter a title" required />
          </div>
          <div>
            <Label>Story</Label>
            <Textarea className="min-h-[200px] w-full" placeholder="Write your story" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="pseudonym">Pseudonym</Label>
            <Input id="pseudonym" placeholder="Enter a pseudonym" required />
          </div>
          <div className="space-y-2">
            <Button className="w-full">Submit</Button>
            <Button className="w-full" variant="destructive">
              Cancel
            </Button>
          </div>
          <div />
        </div>
      </div>
    </div>
  )
}
